version: '3.7'

services:
  db:
    build: ./database
    container_name: db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=${dataSourcePrefix}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  car:
    build: .
    container_name: test
    depends_on:
      - db
    ports:
      - "8000:80"
      - "8080:8080"
      - "9009:9009"
    restart: always
    environment:
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_NAME=test
      - DB_HOST=db
      - DB_PORT=5432
      - PAYARA_ARGS=-d
volumes:
  db_data: